// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlertStatusChange();
void onFRS1Change();
void onFRS2Change();
void onFRS3Change();
void onFRS4Change();
void onFRS5Change();
void onFRS6Change();
void onHighestAccTimeChange();

int alertStatus;
int fRS1;
int fRS2;
int fRS3;
int fRS4;
int fRS5;
int fRS6;
int highestAccTime;

void initProperties(){

  ArduinoCloud.addProperty(alertStatus, READWRITE, ON_CHANGE, onAlertStatusChange);
  ArduinoCloud.addProperty(fRS1, READWRITE, 1 * SECONDS, onFRS1Change);
  ArduinoCloud.addProperty(fRS2, READWRITE, 1 * SECONDS, onFRS2Change);
  ArduinoCloud.addProperty(fRS3, READWRITE, 1 * SECONDS, onFRS3Change);
  ArduinoCloud.addProperty(fRS4, READWRITE, 1 * SECONDS, onFRS4Change);
  ArduinoCloud.addProperty(fRS5, READWRITE, 1 * SECONDS, onFRS5Change);
  ArduinoCloud.addProperty(fRS6, READWRITE, 1 * SECONDS, onFRS6Change);
  ArduinoCloud.addProperty(highestAccTime, READWRITE, ON_CHANGE, onHighestAccTimeChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
